redash bigquery to use user account
cermati/redash pull request #8
Opened 2020-11-17 01:34 UTC by harinibm16

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description
Changes in bigquery datasource to use user account instead of generic service account.
## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

2020-12-03 09:24 UTC, winasforcepta requested changes
Hi, I saw some method signature changes which adding new parameters in the middle. I don't think it's safe. Could you please fix it?

I also have another question that needs to clarify.

2020-12-03 09:24 UTC, winasforcepta commented on redash/query_runner/__init__.py
> +    def get_schema(self, user=None, get_stats=False):
is it really safe to change the signature like this? especially adding a new parameter in the middle.

2020-12-03 10:32 UTC, harinibm16 commented on client/app/components/QueryEditor.jsx
> +                disabled={isExecuteDisabled}
you can check in` redash/client/app/pages/queries/view.js` line 229

2020-12-03 12:07 UTC, harinibm16 commented on redash/query_runner/__init__.py
> +    def get_schema(self, user=None, get_stats=False):
I have updated [aa2d8eb2bf7baa019266bf516de694644f4fe594](https://github.com/cermati/redash/pull/8/commits/aa2d8eb2bf7baa019266bf516de694644f4fe594)

2020-12-14 09:22 UTC, winasforcepta requested changes
Hi, I request another change based on the previous comment. Let me know if it's not clear.

2020-12-14 09:22 UTC, winasforcepta commented on redash/query_runner/__init__.py
> +    def get_schema(self, user=None, get_stats=False):
I mean, it's better to append the new parameters in the end. Consider this case, redash is an opensource project. Let's say we want to rebase to our codebase to the main redash codebase and someone else using this method somewhere else but this guy relies on the signature order, it would fail. I suggest to modify it to
```
def get_schema(self, get_stats=False, user=None):
```
and please do the same thing for the other method that you modify.

2020-12-14 09:42 UTC, winasforcepta approved these changes

2020-12-15 04:20 UTC, merged